POST http://localhost:3333/videos
Content-type: application/json

{
  "title": "video 02",
  "description": "video 02 description",
  "duration": 220
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/262755d1-8446-4fc6-b261-e5bd8b66c2e9
Content-type: application/json

{
  "title": "video 03",
  "description": "video 03 description",
  "duration": 10
}

###
DELETE  http://localhost:3333/videos/262755d1-8446-4fc6-b261-e5bd8b66c2e9
